# Open terminal in your project root, run `docker compose --env-file .env -f docker-compose.yml up -d`

version: '3.8'

services:
  web:
    container_name: ${CONTAINER_NAME}
    image: nginx:latest
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ${HOST_SOURCE_CODE_PATH}:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ${DOCKER_NETWORK}

networks:
  ${DOCKER_NETWORK}:
    external: true
